#!/usr/bin/env python3
"""Local PyInstaller build with hiddenimports for lazy-loaded packages."""

from __future__ import annotations

import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
ICON_FILE = ROOT / "ico" / "RKNHS.ico"

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

TOP_LEVEL_PACKAGES = (
    "about",
    "app",
    "autostart",
    "blockcheck",
    "config",
    "core",
    "diagnostics",
    "discord",
    "dns",
    "donater",
    "folders",
    "hosts",
    "licensing",
    "lists",
    "log",
    "main",
    "orchestra",
    "presets",
    "profile",
    "program_settings",
    "settings",
    "startup",
    "telegram_proxy",
    "themes",
    "ui",
    "updater",
    "utils",
    "vpn_split",
    "windows_features",
    "winws_runtime",
)


def hiddenimports_for_spec() -> list[str]:
    hidden: set[str] = set()
    for pkg in TOP_LEVEL_PACKAGES:
        hidden.update(collect_submodules(pkg))
    hidden.add("jinja2")
    return sorted(hidden)


def datas_for_spec() -> list[tuple[str, str]]:
    datas: list[tuple[str, str]] = []
    blockcheck_data = SRC / "blockcheck" / "data"
    if blockcheck_data.is_dir():
        datas.append((str(blockcheck_data), "blockcheck/data"))
    ico_dir = ROOT / "ico"
    if ico_dir.is_dir():
        datas.append((str(ico_dir), "ico"))
    try:
        datas.extend(collect_data_files("qtawesome"))
    except Exception:
        pass
    return datas


def write_spec() -> Path:
    hiddenimports = hiddenimports_for_spec()
    datas = datas_for_spec()
    spec_path = SRC / "Zapret.local.spec"
    icon_arg = ""
    if ICON_FILE.is_file():
        icon_arg = f"    icon={ICON_FILE.as_posix()!r},\n"
    spec_path.write_text(
        f"""# -*- mode: python ; coding: utf-8 -*-
# Generated by build_pyinstaller.py

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas={datas!r},
    hiddenimports={hiddenimports!r},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='RKNHS',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=True,
{icon_arg})
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='RKNHS',
)
""",
        encoding="utf-8",
    )
    print(f"Wrote {spec_path} ({len(hiddenimports)} hiddenimports, {len(datas)} datas)")
    return spec_path


if __name__ == "__main__":
    write_spec()
