from __future__ import annotations

import os

from lists.core.paths import get_list_final_path, get_list_user_path, get_lists_user_dir


IPSET_VPN_USER = get_list_user_path("ipset-vpn")
IPSET_VPN_FINAL = get_list_final_path("ipset-vpn")


def clear_vpn_ipset() -> None:
    os.makedirs(get_lists_user_dir(), exist_ok=True)
    content = "# VPN Split inactive — no DPI exclusions\n"
    for path in (IPSET_VPN_USER, IPSET_VPN_FINAL):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)


def write_vpn_ipset(entries: list[str]) -> str:
    os.makedirs(get_lists_user_dir(), exist_ok=True)
    normalized = sorted({str(item).strip() for item in entries if str(item or "").strip()})
    header = "# Auto-generated by RKNHS VPN Split — IPs routed via AmneziaWG (excluded from DPI)\n"
    body = "\n".join(normalized)
    content = header + (body + "\n" if body else "")
    with open(IPSET_VPN_USER, "w", encoding="utf-8") as user_file:
        user_file.write(content)
    with open(IPSET_VPN_FINAL, "w", encoding="utf-8") as final_file:
        final_file.write(content)
    return IPSET_VPN_FINAL
