# URLs used by the desktop UI (RKNHS).
# External upstream project links are intentionally not used.

AUTHOR_URL = "https://github.com/Sazzero"

#VERSION_URL = ""  # URL для проверки обновлений
#EXE_UPDATE_URL = ""  # URL для скачивания обновления EXE
DOCS_URL = AUTHOR_URL
INFO_URL = AUTHOR_URL
PRESET_INFO_URL = AUTHOR_URL
PROFILE_INFO_URL = AUTHOR_URL
ANDROID_URL = AUTHOR_URL
BOLVAN_URL = AUTHOR_URL
SUPPORT_DISCUSSIONS_URL = AUTHOR_URL
BLOCKCHECK_DISCUSSIONS_URL = AUTHOR_URL
PROFILE_REQUEST_FORM_URL = AUTHOR_URL

OTHER_LIST_URL = ""
